name: mimi4me
description: Sound analysis.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  tflite_flutter:
  mfcc:
  cupertino_icons: ^1.0.2
  record: ^3.0.3
  path_provider: ^2.0.9
  vibration: 1.7.4-nullsafety.0
  http:
  flutter_dotenv: ^5.0.2
  flutter_spinkit: ^5.1.0
  permission_handler: ^8.0.0+2
  noise_meter: 3.0.0
  flutter_foreground_task: ^3.7.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  flutter_launcher_icons: "^0.9.2"

flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/image/
    - assets/labels.txt
    - assets/saved_model.tflite

flutter_icons:

  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"