name: mimi4me
description: Sound Alert.

publish_to: 'none'

version: 0.0.0+5

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  path_provider: ^2.0.2
  vibration: ^1.7.6
  flutter_dotenv: ^5.0.2
  flutter_spinkit: ^5.1.0
  permission_handler: ^10.0.0
  noise_meter: ^3.1.0
  flutter_foreground_task: ^3.7.3
  get_storage:
  url_launcher:
  tflite_flutter:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.10.0

flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/image/
    - assets/saved_model.tflite

flutter_icons:

  android: "launcher_icon"
  ios: true
  image_path: "assets/image/new_logo_sm.png"